import { View, Text, StyleSheet, ScrollView, TouchableOpacity, SafeAreaView } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '@/constants/colors';
import { typography } from '@/constants/typography';

export default function Terms() {
  const handleBack = () => {
    router.back();
  };

  const handleAccept = () => {
    router.back();
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.backButton} 
          onPress={handleBack}
        >
          <Ionicons name="chevron-back" size={28} color={colors.black[100]} />
        </TouchableOpacity>
        <Text style={styles.title}>Terms of Service</Text>
      </View>

      <ScrollView style={styles.content}>
        <Text style={styles.lastUpdated}>Last Updated: {new Date().toLocaleDateString()}</Text>
        
        <Text style={styles.sectionTitle}>1. Acceptance of Terms</Text>
        <Text style={styles.paragraph}>
          By accessing or using Ink-It, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.
        </Text>

        <Text style={styles.sectionTitle}>2. Description of Service</Text>
        <Text style={styles.paragraph}>
          Ink-It is a mobile application that allows users to convert photos into tattoo designs using artificial intelligence technology. The app processes user-uploaded images through AI to create potential tattoo designs.
        </Text>

        <Text style={styles.sectionTitle}>3. User Content</Text>
        <Text style={styles.paragraph}>
          Images you upload to Ink-It remain your property. However, you grant us a license to process these images to provide our services. We do not claim ownership of your content.
        </Text>
        <Text style={styles.paragraph}>
          You are solely responsible for the images you upload and confirm you have the right to use them.
        </Text>

        <Text style={styles.sectionTitle}>4. Privacy</Text>
        <Text style={styles.paragraph}>
          We collect minimal data to provide our services. For details on what information we collect and how we use it, please refer to our Privacy Policy.
        </Text>

        <Text style={styles.sectionTitle}>5. AI-Generated Content</Text>
        <Text style={styles.paragraph}>
          The tattoo designs generated by our AI are provided "as is" without warranties. We do not guarantee that designs will be suitable for actual tattoos without modification by a professional tattoo artist.
        </Text>

        <Text style={styles.sectionTitle}>6. Subscription and Billing</Text>
        <Text style={styles.paragraph}>
          Ink-It offers free and premium subscription plans. By selecting a premium plan, you agree to pay the subscription fees. You can cancel your subscription at any time through your account settings.
        </Text>

        <Text style={styles.sectionTitle}>7. Limitations</Text>
        <Text style={styles.paragraph}>
          You agree not to use Ink-It to upload, process, or create designs that are offensive, illegal, or infringe on others' rights. We reserve the right to terminate accounts that violate these terms.
        </Text>

        <Text style={styles.sectionTitle}>8. Changes to Terms</Text>
        <Text style={styles.paragraph}>
          We may update these terms from time to time. Continued use of Ink-It after changes constitutes acceptance of the updated terms.
        </Text>

        <Text style={styles.sectionTitle}>9. Contact</Text>
        <Text style={styles.paragraph}>
          If you have any questions about these Terms of Service, please contact us at support@ink-it.com.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white[100],
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    paddingTop: 0,
  },
  backButton: {
    marginRight: 10,
  },
  title: {
    ...typography.heading1({ color: colors.black[100] }),
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  lastUpdated: {
    ...typography.bodySmall({ color: colors.black[100] }),
    marginBottom: 20,
    fontStyle: 'italic',
  },
  sectionTitle: {
    ...typography.heading3({ color: colors.black[100] }),
    marginTop: 20,
    marginBottom: 10,
  },
  paragraph: {
    ...typography.bodyMedium({ color: colors.black[100] }),
    marginBottom: 16,
    lineHeight: 24,
  },
  footer: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: colors.white[300],
  },
  acceptButton: {
    backgroundColor: colors.black[100],
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  acceptButtonText: {
    ...typography.buttonMedium({ color: colors.white[100] }),
  },
}); 